apiVersion: v1
kind: ConfigMap
metadata:
  name: startpage-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1> Proof of the magic of ingresses </h1>
    </br>
    <h1>Kubernetes Hosted  1 </h1>
    <h1><a href="http://20.241.145.4/frontend/">A doua parte</a> </h1>
    </html